var annotated_dup =
[
    [ "Catch", null, [
      [ "Detail", null, [
        [ "Approx", "classCatch_1_1Detail_1_1Approx.html", null ],
        [ "EnumInfo", "structCatch_1_1Detail_1_1EnumInfo.html", null ],
        [ "IsStreamInsertable", "classCatch_1_1Detail_1_1IsStreamInsertable.html", null ]
      ] ],
      [ "detail", null, [
        [ "is_range_impl", "structCatch_1_1detail_1_1is__range__impl.html", null ],
        [ "is_range_impl< T, typename void_type< decltype(begin(std::declval< T >()))>::type >", "structCatch_1_1detail_1_1is__range__impl_3_01T_00_01typename_01void__type_3_01decltype_07begin_0efe009a05f00a00c1e4e06989d122a22.html", null ],
        [ "void_type", "structCatch_1_1detail_1_1void__type.html", null ]
      ] ],
      [ "Generators", null, [
        [ "as", "structCatch_1_1Generators_1_1as.html", null ],
        [ "ChunkGenerator", "classCatch_1_1Generators_1_1ChunkGenerator.html", null ],
        [ "FilterGenerator", "classCatch_1_1Generators_1_1FilterGenerator.html", null ],
        [ "FixedValuesGenerator", "classCatch_1_1Generators_1_1FixedValuesGenerator.html", null ],
        [ "Generators", "classCatch_1_1Generators_1_1Generators.html", null ],
        [ "GeneratorUntypedBase", "classCatch_1_1Generators_1_1GeneratorUntypedBase.html", null ],
        [ "GeneratorWrapper", "classCatch_1_1Generators_1_1GeneratorWrapper.html", null ],
        [ "IGenerator", "structCatch_1_1Generators_1_1IGenerator.html", null ],
        [ "IteratorGenerator", "classCatch_1_1Generators_1_1IteratorGenerator.html", null ],
        [ "MapGenerator", "classCatch_1_1Generators_1_1MapGenerator.html", null ],
        [ "RandomFloatingGenerator", "classCatch_1_1Generators_1_1RandomFloatingGenerator.html", null ],
        [ "RandomIntegerGenerator", "classCatch_1_1Generators_1_1RandomIntegerGenerator.html", null ],
        [ "RangeGenerator", "classCatch_1_1Generators_1_1RangeGenerator.html", null ],
        [ "RepeatGenerator", "classCatch_1_1Generators_1_1RepeatGenerator.html", null ],
        [ "SingleValueGenerator", "classCatch_1_1Generators_1_1SingleValueGenerator.html", null ],
        [ "TakeGenerator", "classCatch_1_1Generators_1_1TakeGenerator.html", null ]
      ] ],
      [ "Matchers", null, [
        [ "Exception", null, [
          [ "ExceptionMessageMatcher", "classCatch_1_1Matchers_1_1Exception_1_1ExceptionMessageMatcher.html", null ]
        ] ],
        [ "Floating", null, [
          [ "WithinAbsMatcher", "structCatch_1_1Matchers_1_1Floating_1_1WithinAbsMatcher.html", null ],
          [ "WithinRelMatcher", "structCatch_1_1Matchers_1_1Floating_1_1WithinRelMatcher.html", null ],
          [ "WithinUlpsMatcher", "structCatch_1_1Matchers_1_1Floating_1_1WithinUlpsMatcher.html", null ]
        ] ],
        [ "Generic", null, [
          [ "PredicateMatcher", "classCatch_1_1Matchers_1_1Generic_1_1PredicateMatcher.html", null ]
        ] ],
        [ "Impl", null, [
          [ "MatchAllOf", "structCatch_1_1Matchers_1_1Impl_1_1MatchAllOf.html", null ],
          [ "MatchAnyOf", "structCatch_1_1Matchers_1_1Impl_1_1MatchAnyOf.html", null ],
          [ "MatcherBase", "structCatch_1_1Matchers_1_1Impl_1_1MatcherBase.html", null ],
          [ "MatcherMethod", "structCatch_1_1Matchers_1_1Impl_1_1MatcherMethod.html", null ],
          [ "MatcherUntypedBase", "classCatch_1_1Matchers_1_1Impl_1_1MatcherUntypedBase.html", null ],
          [ "MatchNotOf", "structCatch_1_1Matchers_1_1Impl_1_1MatchNotOf.html", null ]
        ] ],
        [ "StdString", null, [
          [ "CasedString", "structCatch_1_1Matchers_1_1StdString_1_1CasedString.html", null ],
          [ "ContainsMatcher", "structCatch_1_1Matchers_1_1StdString_1_1ContainsMatcher.html", null ],
          [ "EndsWithMatcher", "structCatch_1_1Matchers_1_1StdString_1_1EndsWithMatcher.html", null ],
          [ "EqualsMatcher", "structCatch_1_1Matchers_1_1StdString_1_1EqualsMatcher.html", null ],
          [ "RegexMatcher", "structCatch_1_1Matchers_1_1StdString_1_1RegexMatcher.html", null ],
          [ "StartsWithMatcher", "structCatch_1_1Matchers_1_1StdString_1_1StartsWithMatcher.html", null ],
          [ "StringMatcherBase", "structCatch_1_1Matchers_1_1StdString_1_1StringMatcherBase.html", null ]
        ] ],
        [ "Vector", null, [
          [ "ApproxMatcher", "structCatch_1_1Matchers_1_1Vector_1_1ApproxMatcher.html", null ],
          [ "ContainsElementMatcher", "structCatch_1_1Matchers_1_1Vector_1_1ContainsElementMatcher.html", null ],
          [ "ContainsMatcher", "structCatch_1_1Matchers_1_1Vector_1_1ContainsMatcher.html", null ],
          [ "EqualsMatcher", "structCatch_1_1Matchers_1_1Vector_1_1EqualsMatcher.html", null ],
          [ "UnorderedEqualsMatcher", "structCatch_1_1Matchers_1_1Vector_1_1UnorderedEqualsMatcher.html", null ]
        ] ]
      ] ],
      [ "always_false", "structCatch_1_1always__false.html", null ],
      [ "AssertionHandler", "classCatch_1_1AssertionHandler.html", null ],
      [ "AssertionInfo", "structCatch_1_1AssertionInfo.html", null ],
      [ "AssertionReaction", "structCatch_1_1AssertionReaction.html", null ],
      [ "AutoReg", "structCatch_1_1AutoReg.html", null ],
      [ "BinaryExpr", "classCatch_1_1BinaryExpr.html", null ],
      [ "Capturer", "classCatch_1_1Capturer.html", null ],
      [ "CaseSensitive", "structCatch_1_1CaseSensitive.html", null ],
      [ "Counts", "structCatch_1_1Counts.html", null ],
      [ "Decomposer", "structCatch_1_1Decomposer.html", null ],
      [ "ExceptionTranslatorRegistrar", "classCatch_1_1ExceptionTranslatorRegistrar.html", null ],
      [ "ExprLhs", "classCatch_1_1ExprLhs.html", null ],
      [ "GeneratorException", "classCatch_1_1GeneratorException.html", null ],
      [ "IConfig", "structCatch_1_1IConfig.html", null ],
      [ "IContext", "structCatch_1_1IContext.html", null ],
      [ "IExceptionTranslator", "structCatch_1_1IExceptionTranslator.html", null ],
      [ "IExceptionTranslatorRegistry", "structCatch_1_1IExceptionTranslatorRegistry.html", null ],
      [ "IGeneratorTracker", "structCatch_1_1IGeneratorTracker.html", null ],
      [ "IMutableContext", "structCatch_1_1IMutableContext.html", null ],
      [ "IMutableEnumValuesRegistry", "structCatch_1_1IMutableEnumValuesRegistry.html", null ],
      [ "IMutableRegistryHub", "structCatch_1_1IMutableRegistryHub.html", null ],
      [ "IRegistryHub", "structCatch_1_1IRegistryHub.html", null ],
      [ "IResultCapture", "structCatch_1_1IResultCapture.html", null ],
      [ "IRunner", "structCatch_1_1IRunner.html", null ],
      [ "is_callable", "structCatch_1_1is__callable.html", null ],
      [ "is_callable< Fun(Args...)>", "structCatch_1_1is__callable_3_01Fun_07Args_8_8_8_08_4.html", null ],
      [ "is_callable_tester", "structCatch_1_1is__callable__tester.html", null ],
      [ "is_range", "structCatch_1_1is__range.html", null ],
      [ "IStream", "structCatch_1_1IStream.html", null ],
      [ "ITestCaseRegistry", "structCatch_1_1ITestCaseRegistry.html", null ],
      [ "ITestInvoker", "structCatch_1_1ITestInvoker.html", null ],
      [ "ITransientExpression", "structCatch_1_1ITransientExpression.html", null ],
      [ "LazyExpression", "classCatch_1_1LazyExpression.html", null ],
      [ "MatcherBase", "structCatch_1_1MatcherBase.html", null ],
      [ "MatchExpr", "classCatch_1_1MatchExpr.html", null ],
      [ "MessageBuilder", "structCatch_1_1MessageBuilder.html", null ],
      [ "MessageInfo", "structCatch_1_1MessageInfo.html", null ],
      [ "MessageStream", "structCatch_1_1MessageStream.html", null ],
      [ "NameAndTags", "structCatch_1_1NameAndTags.html", null ],
      [ "NonCopyable", "classCatch_1_1NonCopyable.html", null ],
      [ "Option", "classCatch_1_1Option.html", null ],
      [ "pluralise", "structCatch_1_1pluralise.html", null ],
      [ "RegistrarForTagAliases", "structCatch_1_1RegistrarForTagAliases.html", null ],
      [ "ResultDisposition", "structCatch_1_1ResultDisposition.html", null ],
      [ "ResultWas", "structCatch_1_1ResultWas.html", null ],
      [ "ReusableStringStream", "classCatch_1_1ReusableStringStream.html", null ],
      [ "RunTests", "structCatch_1_1RunTests.html", null ],
      [ "ScopedMessage", "classCatch_1_1ScopedMessage.html", null ],
      [ "Section", "classCatch_1_1Section.html", null ],
      [ "SectionEndInfo", "structCatch_1_1SectionEndInfo.html", null ],
      [ "SectionInfo", "structCatch_1_1SectionInfo.html", null ],
      [ "ShowDurations", "structCatch_1_1ShowDurations.html", null ],
      [ "SimplePcg32", "classCatch_1_1SimplePcg32.html", null ],
      [ "SourceLineInfo", "structCatch_1_1SourceLineInfo.html", null ],
      [ "StreamEndStop", "structCatch_1_1StreamEndStop.html", null ],
      [ "StringMaker", "structCatch_1_1StringMaker.html", null ],
      [ "StringMaker< bool >", "structCatch_1_1StringMaker_3_01bool_01_4.html", null ],
      [ "StringMaker< Catch::Detail::Approx >", "structCatch_1_1StringMaker_3_01Catch_1_1Detail_1_1Approx_01_4.html", null ],
      [ "StringMaker< char * >", "structCatch_1_1StringMaker_3_01char_01_5_01_4.html", null ],
      [ "StringMaker< char >", "structCatch_1_1StringMaker_3_01char_01_4.html", null ],
      [ "StringMaker< char const * >", "structCatch_1_1StringMaker_3_01char_01const_01_5_01_4.html", null ],
      [ "StringMaker< char[SZ]>", "structCatch_1_1StringMaker_3_01char_0fSZ_0e_4.html", null ],
      [ "StringMaker< double >", "structCatch_1_1StringMaker_3_01double_01_4.html", null ],
      [ "StringMaker< float >", "structCatch_1_1StringMaker_3_01float_01_4.html", null ],
      [ "StringMaker< int >", "structCatch_1_1StringMaker_3_01int_01_4.html", null ],
      [ "StringMaker< long >", "structCatch_1_1StringMaker_3_01long_01_4.html", null ],
      [ "StringMaker< long long >", "structCatch_1_1StringMaker_3_01long_01long_01_4.html", null ],
      [ "StringMaker< R C::* >", "structCatch_1_1StringMaker_3_01R_01C_1_1_5_01_4.html", null ],
      [ "StringMaker< R, typename std::enable_if< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value >::type >", "structCatch_1_1StringMaker_3_01R_00_01typename_01std_1_1enable__if_3_01is__range_3_01R_01_4_1_1ve8233c20b54b69b4771fbd413409d181.html", null ],
      [ "StringMaker< signed char >", "structCatch_1_1StringMaker_3_01signed_01char_01_4.html", null ],
      [ "StringMaker< signed char[SZ]>", "structCatch_1_1StringMaker_3_01signed_01char_0fSZ_0e_4.html", null ],
      [ "StringMaker< std::nullptr_t >", "structCatch_1_1StringMaker_3_01std_1_1nullptr__t_01_4.html", null ],
      [ "StringMaker< std::string >", "structCatch_1_1StringMaker_3_01std_1_1string_01_4.html", null ],
      [ "StringMaker< std::wstring >", "structCatch_1_1StringMaker_3_01std_1_1wstring_01_4.html", null ],
      [ "StringMaker< T * >", "structCatch_1_1StringMaker_3_01T_01_5_01_4.html", null ],
      [ "StringMaker< T[SZ]>", "structCatch_1_1StringMaker_3_01T_0fSZ_0e_4.html", null ],
      [ "StringMaker< unsigned char >", "structCatch_1_1StringMaker_3_01unsigned_01char_01_4.html", null ],
      [ "StringMaker< unsigned char[SZ]>", "structCatch_1_1StringMaker_3_01unsigned_01char_0fSZ_0e_4.html", null ],
      [ "StringMaker< unsigned int >", "structCatch_1_1StringMaker_3_01unsigned_01int_01_4.html", null ],
      [ "StringMaker< unsigned long >", "structCatch_1_1StringMaker_3_01unsigned_01long_01_4.html", null ],
      [ "StringMaker< unsigned long long >", "structCatch_1_1StringMaker_3_01unsigned_01long_01long_01_4.html", null ],
      [ "StringMaker< wchar_t * >", "structCatch_1_1StringMaker_3_01wchar__t_01_5_01_4.html", null ],
      [ "StringMaker< wchar_t const * >", "structCatch_1_1StringMaker_3_01wchar__t_01const_01_5_01_4.html", null ],
      [ "StringRef", "classCatch_1_1StringRef.html", null ],
      [ "TestCase", "classCatch_1_1TestCase.html", null ],
      [ "TestCaseInfo", "structCatch_1_1TestCaseInfo.html", null ],
      [ "TestFailureException", "structCatch_1_1TestFailureException.html", null ],
      [ "TestInvokerAsMethod", "classCatch_1_1TestInvokerAsMethod.html", null ],
      [ "Timer", "classCatch_1_1Timer.html", null ],
      [ "Totals", "structCatch_1_1Totals.html", null ],
      [ "true_given", "structCatch_1_1true__given.html", null ],
      [ "UnaryExpr", "classCatch_1_1UnaryExpr.html", null ],
      [ "UseColour", "structCatch_1_1UseColour.html", null ],
      [ "WaitForKeypress", "structCatch_1_1WaitForKeypress.html", null ],
      [ "WarnAbout", "structCatch_1_1WarnAbout.html", null ]
    ] ],
    [ "rev", null, [
      [ "AsyncAwaitable", "classrev_1_1AsyncAwaitable.html", "classrev_1_1AsyncAwaitable" ],
      [ "AsyncRunnable", "classrev_1_1AsyncRunnable.html", "classrev_1_1AsyncRunnable" ],
      [ "AsyncRunner", "classrev_1_1AsyncRunner.html", null ],
      [ "Await", "classrev_1_1Await.html", "classrev_1_1Await" ],
      [ "BezierSegment", "classrev_1_1BezierSegment.html", "classrev_1_1BezierSegment" ],
      [ "Call", "classrev_1_1Call.html", "classrev_1_1Call" ],
      [ "CampbellTurn", "classrev_1_1CampbellTurn.html", "classrev_1_1CampbellTurn" ],
      [ "CascadingMotion", "classrev_1_1CascadingMotion.html", "classrev_1_1CascadingMotion" ],
      [ "Chassis", "classrev_1_1Chassis.html", "classrev_1_1Chassis" ],
      [ "ChassisSim", "classrev_1_1ChassisSim.html", null ],
      [ "ConstantMotion", "classrev_1_1ConstantMotion.html", "classrev_1_1ConstantMotion" ],
      [ "Correction", "classrev_1_1Correction.html", "classrev_1_1Correction" ],
      [ "DriftlessSim", "classrev_1_1DriftlessSim.html", "classrev_1_1DriftlessSim" ],
      [ "Motion", "classrev_1_1Motion.html", "classrev_1_1Motion" ],
      [ "NoCorrection", "classrev_1_1NoCorrection.html", "classrev_1_1NoCorrection" ],
      [ "Odometry", "classrev_1_1Odometry.html", "classrev_1_1Odometry" ],
      [ "OdometryState", "structrev_1_1OdometryState.html", null ],
      [ "PilonsCorrection", "classrev_1_1PilonsCorrection.html", "classrev_1_1PilonsCorrection" ],
      [ "PilonsSegment", "classrev_1_1PilonsSegment.html", "classrev_1_1PilonsSegment" ],
      [ "PilonsSegmentParams", "structrev_1_1PilonsSegmentParams.html", null ],
      [ "PointVector", "structrev_1_1PointVector.html", null ],
      [ "Pose", "structrev_1_1Pose.html", "structrev_1_1Pose" ],
      [ "ProportionalMotion", "classrev_1_1ProportionalMotion.html", "classrev_1_1ProportionalMotion" ],
      [ "PurePursuitSegment", "classrev_1_1PurePursuitSegment.html", "classrev_1_1PurePursuitSegment" ],
      [ "Reckless", "classrev_1_1Reckless.html", "classrev_1_1Reckless" ],
      [ "RecklessPath", "structrev_1_1RecklessPath.html", "structrev_1_1RecklessPath" ],
      [ "RecklessSegment", "classrev_1_1RecklessSegment.html", "classrev_1_1RecklessSegment" ],
      [ "RecklessTurnSegment", "classrev_1_1RecklessTurnSegment.html", "classrev_1_1RecklessTurnSegment" ],
      [ "RQuantity", "classrev_1_1RQuantity.html", null ],
      [ "SegmentStatus", "structrev_1_1SegmentStatus.html", null ],
      [ "SimpleStop", "classrev_1_1SimpleStop.html", "classrev_1_1SimpleStop" ],
      [ "SkidSteerChassis", "classrev_1_1SkidSteerChassis.html", "classrev_1_1SkidSteerChassis" ],
      [ "Stop", "classrev_1_1Stop.html", null ],
      [ "StraightSegments", "classrev_1_1StraightSegments.html", "classrev_1_1StraightSegments" ],
      [ "Turn", "classrev_1_1Turn.html", "classrev_1_1Turn" ],
      [ "TwoRotationInertialOdometry", "classrev_1_1TwoRotationInertialOdometry.html", "classrev_1_1TwoRotationInertialOdometry" ],
      [ "Velocity", "structrev_1_1Velocity.html", null ]
    ] ],
    [ "sciplot", null, [
      [ "gnuplot", null, [
        [ "angle", "structsciplot_1_1gnuplot_1_1angle.html", null ]
      ] ],
      [ "AxisLabelSpecs", "classsciplot_1_1AxisLabelSpecs.html", "classsciplot_1_1AxisLabelSpecs" ],
      [ "BorderSpecs", "classsciplot_1_1BorderSpecs.html", "classsciplot_1_1BorderSpecs" ],
      [ "Canvas", "classsciplot_1_1Canvas.html", "classsciplot_1_1Canvas" ],
      [ "ColumnIndex", "structsciplot_1_1ColumnIndex.html", "structsciplot_1_1ColumnIndex" ],
      [ "DepthSpecs", "classsciplot_1_1DepthSpecs.html", null ],
      [ "DepthSpecsOf", "classsciplot_1_1DepthSpecsOf.html", "classsciplot_1_1DepthSpecsOf" ],
      [ "DrawSpecs", "classsciplot_1_1DrawSpecs.html", "classsciplot_1_1DrawSpecs" ],
      [ "Figure", "classsciplot_1_1Figure.html", "classsciplot_1_1Figure" ],
      [ "FilledCurvesSpecs", "classsciplot_1_1FilledCurvesSpecs.html", null ],
      [ "FilledCurvesSpecsOf", "classsciplot_1_1FilledCurvesSpecsOf.html", "classsciplot_1_1FilledCurvesSpecsOf" ],
      [ "FillSpecs", "classsciplot_1_1FillSpecs.html", null ],
      [ "FillSpecsOf", "classsciplot_1_1FillSpecsOf.html", "classsciplot_1_1FillSpecsOf" ],
      [ "FillStyleSpecs", "classsciplot_1_1FillStyleSpecs.html", "classsciplot_1_1FillStyleSpecs" ],
      [ "FontSpecs", "classsciplot_1_1FontSpecs.html", null ],
      [ "FontSpecsOf", "classsciplot_1_1FontSpecsOf.html", "classsciplot_1_1FontSpecsOf" ],
      [ "FrameSpecs", "classsciplot_1_1FrameSpecs.html", null ],
      [ "FrameSpecsOf", "classsciplot_1_1FrameSpecsOf.html", "classsciplot_1_1FrameSpecsOf" ],
      [ "GridSpecs", "classsciplot_1_1GridSpecs.html", "classsciplot_1_1GridSpecs" ],
      [ "GridSpecsBase", "classsciplot_1_1GridSpecsBase.html", "classsciplot_1_1GridSpecsBase" ],
      [ "HistogramStyleSpecs", "classsciplot_1_1HistogramStyleSpecs.html", "classsciplot_1_1HistogramStyleSpecs" ],
      [ "LayoutSpecs", "classsciplot_1_1LayoutSpecs.html", null ],
      [ "LayoutSpecsOf", "classsciplot_1_1LayoutSpecsOf.html", "classsciplot_1_1LayoutSpecsOf" ],
      [ "LegendSpecs", "classsciplot_1_1LegendSpecs.html", "classsciplot_1_1LegendSpecs" ],
      [ "LineSpecs", "classsciplot_1_1LineSpecs.html", null ],
      [ "LineSpecsOf", "classsciplot_1_1LineSpecsOf.html", "classsciplot_1_1LineSpecsOf" ],
      [ "OffsetSpecs", "classsciplot_1_1OffsetSpecs.html", null ],
      [ "OffsetSpecsOf", "classsciplot_1_1OffsetSpecsOf.html", "classsciplot_1_1OffsetSpecsOf" ],
      [ "Overload", "structsciplot_1_1Overload.html", null ],
      [ "Plot", "classsciplot_1_1Plot.html", "classsciplot_1_1Plot" ],
      [ "Plot2D", "classsciplot_1_1Plot2D.html", "classsciplot_1_1Plot2D" ],
      [ "Plot3D", "classsciplot_1_1Plot3D.html", "classsciplot_1_1Plot3D" ],
      [ "PointSpecs", "classsciplot_1_1PointSpecs.html", null ],
      [ "PointSpecsOf", "classsciplot_1_1PointSpecsOf.html", "classsciplot_1_1PointSpecsOf" ],
      [ "ShowSpecs", "classsciplot_1_1ShowSpecs.html", null ],
      [ "ShowSpecsOf", "classsciplot_1_1ShowSpecsOf.html", "classsciplot_1_1ShowSpecsOf" ],
      [ "Specs", "classsciplot_1_1Specs.html", "classsciplot_1_1Specs" ],
      [ "StringOrDouble", "structsciplot_1_1StringOrDouble.html", "structsciplot_1_1StringOrDouble" ],
      [ "TextSpecs", "classsciplot_1_1TextSpecs.html", null ],
      [ "TextSpecsOf", "classsciplot_1_1TextSpecsOf.html", "classsciplot_1_1TextSpecsOf" ],
      [ "TicsSpecs", "classsciplot_1_1TicsSpecs.html", "classsciplot_1_1TicsSpecs" ],
      [ "TicsSpecsBaseOf", "classsciplot_1_1TicsSpecsBaseOf.html", "classsciplot_1_1TicsSpecsBaseOf" ],
      [ "TicsSpecsMajor", "classsciplot_1_1TicsSpecsMajor.html", "classsciplot_1_1TicsSpecsMajor" ],
      [ "TicsSpecsMinor", "classsciplot_1_1TicsSpecsMinor.html", "classsciplot_1_1TicsSpecsMinor" ],
      [ "TitleSpecs", "classsciplot_1_1TitleSpecs.html", null ],
      [ "TitleSpecsOf", "classsciplot_1_1TitleSpecsOf.html", "classsciplot_1_1TitleSpecsOf" ]
    ] ],
    [ "Approx", "classApprox.html", null ],
    [ "Canvas", "classCanvas.html", "classCanvas" ],
    [ "Catch_global_namespace_dummy", "structCatch__global__namespace__dummy.html", null ],
    [ "Figure", "classFigure.html", "classFigure" ],
    [ "Plot2D", "classPlot2D.html", "classPlot2D" ]
];