var dir_26dfe2786748266668b78b9d6e0f0feb =
[
    [ "AxisLabelSpecs.hpp", "AxisLabelSpecs_8hpp_source.html", null ],
    [ "BorderSpecs.hpp", "BorderSpecs_8hpp_source.html", null ],
    [ "DepthSpecsOf.hpp", "DepthSpecsOf_8hpp_source.html", null ],
    [ "DrawSpecs.hpp", "DrawSpecs_8hpp_source.html", null ],
    [ "FilledCurvesSpecsOf.hpp", "FilledCurvesSpecsOf_8hpp_source.html", null ],
    [ "FillSpecsOf.hpp", "FillSpecsOf_8hpp_source.html", null ],
    [ "FillStyleSpecs.hpp", "FillStyleSpecs_8hpp_source.html", null ],
    [ "FontSpecsOf.hpp", "FontSpecsOf_8hpp_source.html", null ],
    [ "FrameSpecsOf.hpp", "FrameSpecsOf_8hpp_source.html", null ],
    [ "GridSpecs.hpp", "GridSpecs_8hpp_source.html", null ],
    [ "GridSpecsBase.hpp", "GridSpecsBase_8hpp_source.html", null ],
    [ "HistogramStyleSpecs.hpp", "HistogramStyleSpecs_8hpp_source.html", null ],
    [ "LabelSpecs.hpp", "LabelSpecs_8hpp_source.html", null ],
    [ "LayoutSpecs.hpp", "LayoutSpecs_8hpp_source.html", null ],
    [ "LegendSpecs.hpp", "LegendSpecs_8hpp_source.html", null ],
    [ "LineSpecsOf.hpp", "LineSpecsOf_8hpp_source.html", null ],
    [ "OffsetSpecsOf.hpp", "OffsetSpecsOf_8hpp_source.html", null ],
    [ "PointSpecsOf.hpp", "PointSpecsOf_8hpp_source.html", null ],
    [ "ShowSpecsOf.hpp", "ShowSpecsOf_8hpp_source.html", null ],
    [ "Specs.hpp", "Specs_8hpp_source.html", null ],
    [ "TextSpecsOf.hpp", "TextSpecsOf_8hpp_source.html", null ],
    [ "TicsSpecs.hpp", "TicsSpecs_8hpp_source.html", null ],
    [ "TicsSpecsBaseOf.hpp", "TicsSpecsBaseOf_8hpp_source.html", null ],
    [ "TicsSpecsMajor.hpp", "TicsSpecsMajor_8hpp_source.html", null ],
    [ "TicsSpecsMinor.hpp", "TicsSpecsMinor_8hpp_source.html", null ],
    [ "TitleSpecsOf.hpp", "TitleSpecsOf_8hpp_source.html", null ]
];