var searchData=
[
  ['v0_202_20and_20v0_203_20see_20the_20a_20href_20https_3a_20sciplot_20github_20io_20tutorials_20tutorials_20a_20and_20the_20a_20href_20https_3a_20sciplot_20github_20io_20api_20api_20documentation_20a_20for_20the_20new_20version_0',['&lt;strong&gt;! WARNING !&lt;/strong&gt; sciplot has been redesigned and there were breaking API changes between v0.2 and v0.3. See the &lt;a href=&quot;https://sciplot.github.io/tutorials/&quot; &gt;tutorials&lt;/a&gt; and the &lt;a href=&quot;https://sciplot.github.io/api/&quot; &gt;API documentation&lt;/a&gt; for the new version.',['../md_sciplot_2docs_2website_2index.html#autotoc_md25',1,'']]],
  ['v0_202_20and_20v0_203_20see_20the_20tutorials_20https_3a_20sciplot_20github_20io_20tutorials_20and_20the_20api_20documentation_20https_3a_20sciplot_20github_20io_20api_20for_20the_20new_20version_1',['**! WARNING !** sciplot has been redesigned and there were breaking API changes between v0.2 and v0.3. See the [tutorials](https://sciplot.github.io/tutorials/) and the [API documentation](https://sciplot.github.io/api/) for the new version.',['..//github/workspace/sciplot/README.md#autotoc_md56',1,'']]],
  ['v0_203_20see_20the_20a_20href_20https_3a_20sciplot_20github_20io_20tutorials_20tutorials_20a_20and_20the_20a_20href_20https_3a_20sciplot_20github_20io_20api_20api_20documentation_20a_20for_20the_20new_20version_2',['&lt;strong&gt;! WARNING !&lt;/strong&gt; sciplot has been redesigned and there were breaking API changes between v0.2 and v0.3. See the &lt;a href=&quot;https://sciplot.github.io/tutorials/&quot; &gt;tutorials&lt;/a&gt; and the &lt;a href=&quot;https://sciplot.github.io/api/&quot; &gt;API documentation&lt;/a&gt; for the new version.',['../md_sciplot_2docs_2website_2index.html#autotoc_md25',1,'']]],
  ['v0_203_20see_20the_20tutorials_20https_3a_20sciplot_20github_20io_20tutorials_20and_20the_20api_20documentation_20https_3a_20sciplot_20github_20io_20api_20for_20the_20new_20version_3',['**! WARNING !** sciplot has been redesigned and there were breaking API changes between v0.2 and v0.3. See the [tutorials](https://sciplot.github.io/tutorials/) and the [API documentation](https://sciplot.github.io/api/) for the new version.',['..//github/workspace/sciplot/README.md#autotoc_md56',1,'']]],
  ['value_4',['value',['../structsciplot_1_1ColumnIndex.html#a6695c111a5d8cba1b02354bc353c0d82',1,'sciplot::ColumnIndex::value'],['../structsciplot_1_1StringOrDouble.html#afddc9bc47160bbdf537bd9419dd56864',1,'sciplot::StringOrDouble::value']]],
  ['values_20are_20present_5',['Plotting broken curves when NaN values are present',['../md_sciplot_2docs_2website_2tutorials.html#autotoc_md46',1,'']]],
  ['velocity_6',['Velocity',['../structrev_1_1Velocity.html',1,'rev']]],
  ['version_7',['version',['..//github/workspace/sciplot/README.md#autotoc_md56',1,'**! WARNING !** sciplot has been redesigned and there were breaking API changes between v0.2 and v0.3. See the [tutorials](https://sciplot.github.io/tutorials/) and the [API documentation](https://sciplot.github.io/api/) for the new version.'],['../md_sciplot_2docs_2website_2index.html#autotoc_md25',1,'&lt;strong&gt;! WARNING !&lt;/strong&gt; sciplot has been redesigned and there were breaking API changes between v0.2 and v0.3. See the &lt;a href=&quot;https://sciplot.github.io/tutorials/&quot; &gt;tutorials&lt;/a&gt; and the &lt;a href=&quot;https://sciplot.github.io/api/&quot; &gt;API documentation&lt;/a&gt; for the new version.']]],
  ['void_5ftype_8',['void_type',['../structCatch_1_1detail_1_1void__type.html',1,'Catch::detail']]]
];
